#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.

# create a symbolic link (-s optional) between the Nginx configuration
# file and the enabled sites directory
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx restart
# terminates the first nginx process ID
kill "$(pgrep 'nginx' | head -1)"
