#!/usr/bin/env bash
# a Bash script that stops 4-to_infinity_and_beyond process.

pid=$(pgrep -f "4-to_infinity_and_beyond")

if [ -n "$pid" ]; then
    # Send a termination signal (SIGTERM) to the process
    kill "$pid"
    # echo "Terminated"
else
    echo "Process '4-to_infinity_and_beyond' not found."
fi
