#!/usr/bin/env bash
# a Bash script that stops 4-to_infinity_and_beyond process.

pid=$(pgrep -f "7-highlander")

if [ -n "$pid" ]; then
    # Send a termination signal (SIGTERM) to the process
    kill -9 "$pid"
    # echo "Terminated"
else
    echo "Process '7-highlander' not found."
fi
