#!/usr/bin/env bash
# a Bash script that displays the content of the file /etc/passwd

#!/bin/bash

# Use a pipe to read lines from /etc/passwd
while IFS=: read -r username _ uid _ _ home_directory _; do
    echo "$username:$uid:$home_directory"
done < /etc/passwd
