#!/usr/bin/env bash
# a Bash script that gives you information about the school file

# Define the file path
file_path="school"

# Check if the file exists
if [ -e "$file_path" ]; then
    echo "school file exists"
    
    # Check if the file is a directory
    if [ -d "$file_path" ]; then
	    echo "school file is not empty"
    else
	    # Check if the file is empty
	    if [ -s "$file_path" ]; then
		    echo "school file is not empty"
	    else
		    echo "school file is empty"
	    fi

	    # Check if the file is a regular file
	    if [ -f "$file_path" ]; then
		    echo "school is a regular file"
	    fi
    fi
else
    echo "school file does not exist"
fi
